### ISSUE TITLE
vectorization fails if text field is longer than 77 words

### ISSUE THREAD

**Issue by StefanBogdan** [weaviate/multi2vec-clip-inference#19]

**Comment by antas-marcin** [comment]
looks like there's a hard limit of 77 tokens in openai-clip-vit-base-patch16 model which can't be overcome, maybe we should deprecate this model? or change it to https://huggingface.co/openai/clip-vit-base-patch32?

**Comment by StefanBogdan** [comment]
Hmm, if it cannot be overwritten then this is a model configuration and not Weaviate limitation. We can deprecated it indeed and use a new-er one/ones.

I am closing this Issue in this case. Feel free to open if needed.
